/**
 * @CLAUDE_CONTEXT
 * Package : packages/flow-engine
 * File    : src/types.ts
 * Role    : Core type definitions for the Flow Engine v3.
 *           All interfaces and the NodeType union must match exactly.
 * Exports : NodeType, FlowNode, FlowEdge, FlowDefinition, TriggerConfig,
 *           ExecutionContext, Condition, ConditionGroup, RiskBreakdown,
 *           CollectInfoConfig, CollectInfoQuestion
 * DO NOT  : Import from @lynkbot/db or apps/*
 */

// ── Node Types ────────────────────────────────────────────────────────────────

export type NodeType =
  // Legacy trigger node — kept for backward compat with flows saved before v3.
  // The engine trigger-node lookup accepts both TRIGGER and the typed variants below.
  | 'TRIGGER'
  // Typed trigger nodes generated by the v3 wizard (preferred going forward)
  | 'TRIGGER_INBOUND_KEYWORD'   // keyword-match entry point
  | 'TRIGGER_ORDER_EVENT'       // order lifecycle event entry point
  | 'TRIGGER_TIME_SINCE_EVENT'  // time-based scheduled entry point
  // Action nodes
  | 'SEND_TEMPLATE'
  | 'SEND_TEXT'
  | 'SEND_INTERACTIVE'
  | 'SEND_MEDIA'
  | 'DELAY'
  | 'WAIT_FOR_REPLY'
  | 'IF_CONDITION'
  | 'KEYWORD_ROUTER'
  | 'TAG_BUYER'
  | 'UPDATE_BUYER'
  | 'SEND_WINDOW'
  | 'RATE_LIMIT'
  | 'SEGMENT_QUALITY_GATE'
  | 'END_FLOW'
  | 'START_SCHEDULING'   // terminal — hands off to scheduling state machine
  | 'ACTIVATE_PLAYBOOK'  // terminal — activates a specific AI Playbook for next AI turn
  | 'COLLECT_INFO'       // sequential question collection from buyer (new in v3)
  | 'NOTIFY_STAFF'       // sends a WhatsApp text to a specific staff member
  | 'AGENT';             // embedded conversational scheduling agent

// ── Trigger Types (stored in flowDefinitions.triggerType column) ──────────────
// Note: TRIGGER_TIME_SINCE_EVENT flows use 'time_based' as the DB triggerType.
// TRIGGER_INBOUND_KEYWORD  → 'inbound_keyword'
// TRIGGER_ORDER_EVENT      → 'order_event'
// TRIGGER_TIME_SINCE_EVENT → 'time_based'

export type TriggerType =
  | 'button_click'
  | 'broadcast'
  | 'time_based'
  | 'inbound_keyword'
  | 'order_event';

export type OrderEvent =
  | 'payment_confirmed'
  | 'shipped'
  | 'delivered'
  | 'payment_failed';

export interface TriggerConfig {
  triggerType: TriggerType;
  /** For button_click: the expected button payload prefix (e.g. 'flow:') */
  buttonPayloadPrefix?: string;
  /** For time_based: cron expression */
  cronExpression?: string;
  /** For inbound_keyword: keywords to match */
  keywords?: string[];
  /** For broadcast: segment filter */
  segmentFilter?: SegmentFilter;
  /** For order_event: which event fires this flow */
  event?: OrderEvent;
  /** For time_since_event: duration + unit */
  duration?: number;
  unit?: 'minutes' | 'hours' | 'days';
}

export interface SegmentFilter {
  tags?: string[];
  minTotalOrders?: number;
  maxTotalOrders?: number;
  lastOrderWithinDays?: number;
  preferredLanguage?: string;
}

// ── Node Config Types (per node type) ────────────────────────────────────────

export interface SendTemplateConfig {
  templateName: string;
  languageCode?: string;
  /** Components with variable templates e.g. {{buyer.name}} */
  components?: Array<{
    type: string;
    parameters?: Array<{
      type: string;
      text?: string;
    }>;
  }>;
}

export interface SendTextConfig {
  /** Message body, may contain {{buyer.name}}, {{answers.varName}} etc. */
  message: string;
}

export interface SendInteractiveConfig {
  type: 'button' | 'list';
  headerText?: string;
  bodyText: string;
  footerText?: string;
  buttons?: Array<{ id: string; title: string }>;
  sections?: Array<{ title: string; rows: Array<{ id: string; title: string; description?: string }> }>;
}

export interface SendMediaConfig {
  mediaType: 'image' | 'video' | 'document' | 'audio';
  mediaUrl: string;
  caption?: string;
}

export interface DelayConfig {
  delayMs: number;
}

export interface WaitForReplyConfig {
  /** Optional timeout in ms after which flow continues (0 = infinite) */
  timeoutMs?: number;
}

export interface IfConditionConfig {
  conditions: ConditionGroup;
}

export interface KeywordRouterConfig {
  /** Each keyword maps to an output port by its array index */
  keywords: string[];
  /** Default port when no keyword matches */
  defaultAction?: string;
}

export interface TagBuyerConfig {
  action: 'add' | 'remove';
  tag: string;
}

export interface UpdateBuyerConfig {
  field: 'displayName' | 'notes' | 'preferredLanguage';
  value: string;
}

export interface SendWindowConfig {
  /** Start hour (0-23) in Jakarta time UTC+7 */
  startHour: number;
  /** End hour (0-23) in Jakarta time UTC+7 */
  endHour: number;
}

export interface RateLimitConfig {
  /** Max sends per hour (default 1000) */
  maxPerHour?: number;
}

export interface SegmentQualityGateConfig {
  requireOrders?: boolean;
  requireInboundHistory?: boolean;
}

export interface EndFlowConfig {
  reason?: string;
}

export interface StartSchedulingConfig {
  /** Optional intro message sent to buyer before handing off */
  introMessage?: string;
  /** Optional consultation type label (e.g. "Skin Consultation") */
  consultationType?: string;
  /** Staff UUID to receive the booking confirmation notification */
  assignedStaffId?: string;
  /** Service UUID — when set, wizard pre-selects this service for the scheduling agent */
  serviceId?: string;
  /**
   * How appointments for this service are confirmed.
   * 'staff_confirm' (default) — staff must reply before buyer is notified.
   * 'instant' — auto-confirm, notify staff after the fact.
   * Stored in playbookOverride JSONB so the scheduling handler can read it.
   */
  confirmationModel?: 'instant' | 'staff_confirm';
}

export interface ActivatePlaybookConfig {
  /** The intent key of the playbook to activate (e.g. 'SCHEDULING', 'PRODUCT_INQUIRY') */
  intentKey: string;
}

export interface NotifyStaffConfig {
  /** UUID of the staff member to notify */
  staffId: string;
  /** Message body — supports {{buyer.name}}, {{buyer.phone}}, {{buyer.totalOrders}} */
  message: string;
}

// ── COLLECT_INFO node types (new in v3) ───────────────────────────────────────

export interface CollectInfoQuestion {
  /** Unique id within the node, e.g. 'q1' */
  id: string;
  /** Message sent to buyer asking this question */
  promptText: string;
  /** Stored in ctx.variables['answers.{variableName}'] after buyer replies */
  variableName: string;
  type: 'text' | 'choice';
  /** If type='choice', these become WhatsApp button labels (max 3) */
  choices?: string[];
  required: boolean;
}

export interface CollectInfoConfig {
  questions: CollectInfoQuestion[];
  /** What to do after all questions are answered */
  onComplete: 'continue' | 'end';
  /** Per-question reply timeout in ms. Default: 86400000 (24h) */
  timeoutMs?: number;
}

// ── AGENT config ──────────────────────────────────────────────────────────────

export interface AgentStaffNotification {
  staffId: string;
  message: string;
}

export interface AgentAction {
  label: string;
  instructions: string;
}

export interface AgentConfig {
  instructions: string;
  memoryEnabled: boolean;
  introMessage?: string;
  consultationType?: string;
  assignedStaffId?: string;
  staffMessage?: string;
  additionalStaffNotifications?: AgentStaffNotification[];
  actions?: [AgentAction, AgentAction];
}

// ── NodeConfig union ──────────────────────────────────────────────────────────

export type NodeConfig =
  | SendTemplateConfig
  | SendTextConfig
  | SendInteractiveConfig
  | SendMediaConfig
  | DelayConfig
  | WaitForReplyConfig
  | IfConditionConfig
  | KeywordRouterConfig
  | TagBuyerConfig
  | UpdateBuyerConfig
  | SendWindowConfig
  | RateLimitConfig
  | SegmentQualityGateConfig
  | EndFlowConfig
  | StartSchedulingConfig
  | ActivatePlaybookConfig
  | CollectInfoConfig
  | NotifyStaffConfig
  | AgentConfig
  | Record<string, unknown>;

// ── Graph Structures ──────────────────────────────────────────────────────────

export interface FlowNode {
  id: string;
  type: NodeType;
  label?: string;
  config: NodeConfig;
  /** Visual position on the canvas */
  position?: { x: number; y: number };
}

export interface FlowEdge {
  id: string;
  /** Source node id */
  source: string;
  /** Target node id */
  target: string;
  /**
   * Output port from source node:
   * - 'default' — normal/fallthrough
   * - 'true' / 'false' — from IF_CONDITION
   * - 'outside' — from SEND_WINDOW (outside time window)
   * - 'excluded' — from SEGMENT_QUALITY_GATE
   * - string index — from KEYWORD_ROUTER ('0', '1', etc.)
   */
  sourcePort?: string;
}

export interface FlowDefinition {
  nodes: FlowNode[];
  edges: FlowEdge[];
}

// ── Condition Types ───────────────────────────────────────────────────────────

export type ConditionOperator =
  | 'equals'
  | 'not_equals'
  | 'contains'
  | 'not_contains'
  | 'greater_than'
  | 'less_than'
  | 'is_set'
  | 'is_not_set'
  | 'days_since'
  | 'includes_tag'
  | 'not_includes_tag';

export type ConditionField =
  | 'buyer.name'
  | 'buyer.phone'
  | 'buyer.totalOrders'
  | 'buyer.tags'
  | 'buyer.lastOrderAt'
  | 'trigger.type'
  | 'trigger.buttonPayload'
  | `flow.variable.${string}`
  | `answers.${string}`;

export interface Condition {
  field: ConditionField | string;
  operator: ConditionOperator;
  value?: string | number | boolean;
}

export interface ConditionGroup {
  logic: 'AND' | 'OR';
  conditions: Condition[];
}

// ── Execution Context ─────────────────────────────────────────────────────────

export interface BuyerContext {
  id: string;
  waPhone: string;
  name: string;
  totalOrders: number;
  tags: string[];
  lastOrderAt?: Date | null;
  doNotContact: boolean;
  preferredLanguage: string;
  notes?: string | null;
  displayName?: string | null;
  activeFlowCount: number;
}

export interface TriggerContext {
  type: TriggerType | 'order_event';
  buttonPayload?: string;
  messageText?: string;
  conversationId?: string;
  /** Set when triggered by an order lifecycle event */
  orderId?: string;
}

export interface ExecutionContext {
  executionId: string;
  flowId: string;
  tenantId: string;
  buyerId: string;
  buyer: BuyerContext;
  trigger: TriggerContext;
  /** Flow-scoped runtime variables. COLLECT_INFO stores answers here as 'answers.{variableName}'. */
  variables: Record<string, unknown>;
  executionLog: ExecutionLogEntry[];
  wabaId?: string;
}

export interface ExecutionLogEntry {
  nodeId: string;
  nodeType: NodeType;
  timestamp: string;
  status: 'ok' | 'skipped' | 'error' | 'waiting';
  skipReason?: string;
  error?: string;
  meta?: Record<string, unknown>;
}

// ── Risk Score ────────────────────────────────────────────────────────────────

export interface RiskBreakdown {
  broadcastFrequencyScore: number;
  templateQualityScore: number;
  blockProxyScore: number;
  optInConfidenceScore: number;
  sendSpeedScore: number;
  total: number;
}
